### ISSUE TITLE
Feature Request for `filter_select` and `filter_checkbox`

### ISSUE THREAD

**Issue by ultinomics** [rstudio/crosstalk#10]
For `filter_select`, the ability to type in a name, filter, and select by hitting return. At the moment, one can only scroll and click to select. Any keyboard interactions just disables any option to select anything.

For `filter_checkbox`, the option to set up a grid of checkboxes. Currently, it spits out a list, one item after the other. Were one to, say, select from a set of US states, one would get a 50 rows of checkboxes.

**Comment by jcheng5** [comment]
Both fixed (for the latter, see the new `columns` argument). Thanks for the feedback!
