### ISSUE TITLE
filter_select and filter_checkbox tamper with flexdashboard navbar

### ISSUE THREAD

**Issue by voxnonecho** [rstudio/crosstalk#11]
I've been experimenting with `crosstalk` in a `flexdashboard` and I noticed `filter_select` and `filter_checkbox` change the navbar color to black and the text to grey.

Minimal reprex:

``````

---
title: "Untitled"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill

---

Page 1
===================================== 

Column 
-----------------------------------------------------------------------

### Chart A

```{r}
library(htmltools)
library(crosstalk)
library(leaflet)

sd <- SharedData$new(quakes)

filter_slider("mag", "Magnitude", sd, column = ~mag, step = 0.1)
filter_select("class", "Class", sd, group = ~depth)
leaflet(sd) %>% addTiles() %>% addMarkers()
```
``````

**Comment by jcheng5** [comment]
Thanks. I've hacked in a fix by downgrading the version of bootstrap to 3.3.2. I think all the versions of flexdashboard, rmarkdown, and shiny you might come across now would be running newer versions of bootstrap than that, which will prevent us from overriding their CSS.
