### ISSUE TITLE
Can't create working SharedData - bad install?

### ISSUE THREAD

**Issue by jonspring** [rstudio/crosstalk#122]
I'm having a very basic problem with my `crosstalk` installation where I can't run boilerplate code. Am I missing something obvious here? First tried within an R Markdown HTML, but same issue after restarting R and running the code in an R script.

I'm running R 4.1.0 (2021-05-18) on a PC (x86_64-w64-mingw32)

```
library(ggplot2) # v3.3.5
library(crosstalk) # v1.2.0   also tried using crosstalk 1.2.0.9000 with same results
#> Warning: package 'crosstalk' was built under R version 4.1.3
ggplot(iris, aes(Petal.Length, Petal.Width, color = Species)) + geom_point()
#[plot looks fine]


shared_iris <- SharedData$new(iris)
ggplot(shared_iris, aes(Petal.Length, Petal.Width, color = Species)) + geom_point()
#> Error: `data` must be a data frame, or other object coercible by `fortify()`, not an S3 object with class SharedData/R6.
Created on 2022-03-24 by the reprex package (v2.0.0)
```

**Comment by jcheng5** [comment]
Hi there, ggplot2 alone isn't compatible with crosstalk. But you can add plotly to make it work:

```r
library(ggplot2)
library(crosstalk)
library(plotly)

shared_iris <- SharedData$new(iris)
gg <- ggplot(shared_iris, aes(Petal.Length, Petal.Width, color = Species)) + geom_point()
ggplotly(gg)
```

**Comment by jonspring** [comment]
Ah, I see!
The `gg <- ggplot(...` line errors out if run before `library(plotly)` but runs ok after that line has run. I presume that has something to do with how `plotly` masks other functions like `ggplot2::last_plot` or `graphics::layout`. Thank you.
