### ISSUE TITLE
SharedData objects should have the same group by default

### ISSUE THREAD

**Issue by cpsievert** [rstudio/crosstalk#15]
I know this is an opinion, but I think ~90% of the time this is the right behavior. Sometimes it's confusing even to me why a link isn't working -- then I eventually remember to match the group argument in each `SharedData$new()` call.

**Comment by jcheng5** [comment]
I'm hoping this will get easier when I implement proper transform methods on `SharedData`. But I really hate the idea of the same group by default, sorry.
