### ISSUE TITLE
Shared levels between plots

### ISSUE THREAD

**Issue by Lucas-Maciel** [rstudio/crosstalk#155]
Hi,

I'm trying to make a dashboard where in each tab I have plots/tables for different time points, always subsetting the same DF in long format. The first tab works fine 

```
#Load table
counts <- readRDS(paste0(projectFolder,"AS34_melted_counts.rds"))
counts$Dose <- factor(counts$Dose)

shared_6h <- counts[counts$TimePoint == "6H" | counts$TimePoint == "-7D" ,] %>%
  SharedData$new(.,group = "counts_subset")

filter_select("Gene_6h", "Choose an Gene", shared_6h, ~Gene, multiple = FALSE)

plot_ly(shared_6h, x= ~TimePoint, y = ~normCounts, color = ~Dose,group=~Dose, type = "box",boxpoints = "all",
        colors = c("#00BFC4","#F8766D")) %>%
   layout(boxmode = "group")
```
![Image](https://github.com/user-attachments/assets/105243f2-497d-4d62-a1fb-a7200fb1051c)

But then, when I run the second tab, it still remembers the level 6H that was used in the first tab

```
shared_24h <- counts[counts$TimePoint == "24H" | counts$TimePoint == "-7D" ,] %>%
  SharedData$new()

filter_select("Gene_24h", "Choose an Gene", shared_24h, ~Gene, multiple = FALSE)


plot_ly(shared_24h, x= ~TimePoint, y = ~normCounts, color = ~Dose,group=~Dose, type = "box",boxpoints = "all",
        colors = c("#00BFC4","#F8766D")) %>%
   layout(boxmode = "group")

```
![Image](https://github.com/user-attachments/assets/ba5c00c2-958c-4a3b-976d-e607fa6eab30)

And the same happens for every other tab, always adding the previous one plotted.

![Image](https://github.com/user-attachments/assets/5ad348a6-65aa-4c44-9fcc-956f6e87eba2)

I tried to use the group argument in  SharedData$new() but didn't solve my issue.  Am I doing something wrong? 

Thank you in advance

**Comment by zpeng2020** [comment]
The website said crosstalk didn't support aggregated view...I'm wondering if it's related to this issue? Or if the website information is out of date. I think function highlight() from plotly package could work this out?
