### ISSUE TITLE
any priority for conversion of htmlwidgets

### ISSUE THREAD

**Issue by timelyportfolio** [rstudio/crosstalk#17]
Likely premature, but is there any order of priority for conversion of `htmlwidgets` to `crosstalk`.  It seems `leaflet`, `plotly`, and `parcoords` offer some level of support.  `DT` had support, but I think is now obsolete given the new API.  I thought `dygraphs` would be very interesting.

**Comment by jcheng5** [comment]
DT support has been restored on the `joe/feature/crosstalk` branch (at least to the level that it was supported before).

leaflet supports it on the `crosstalk3` branch. Probably no reason now not to merge to master.

I feel like @jjallaire took a look at dygraphs but it wasn't a perfect fit. Would each series map to a key? How would you brush?

**Comment by timelyportfolio** [comment]
I am not sure what I have in my mind, but I wanted to be careful not to duplicate efforts or push something in the wrong direction.  Thanks for the insight!

**Comment by ogansell** [comment]
The ability to use crosstalk::filter_select would be pretty cool. Does the fact that dygraph uses xts objects rather than a dataframe pose problems??
