### ISSUE TITLE
Add support for leaflet sf

### ISSUE THREAD

**Issue by tiernanmartin** [rstudio/crosstalk#28]
When using a leaflet map that relies on `sf` data, the linking doesn't work:

``` r
  library(crosstalk)
  library(d3scatter)
  library(leaflet)
  library(sf)
  library(tidyverse)
  
  demo(nc, ask = FALSE, echo = FALSE, verbose = FALSE)
  
  nc_pts_WGS84 <- nc %>% st_transform(4326) %>% st_centroid()
  
  shared_nc <- SharedData$new(nc_pts_WGS84)
  
  bscols(leaflet(width = "100%", height = 300) %>%
           addTiles() %>%
           addMarkers(data = nc_pts_WGS84),
         d3scatter(shared_nc, ~BIR74, ~SID79, width = "100%", height = 300)
         
  )
```
A screenshot of the result (notice the absence of the leaflet rectangular select tool):

![crosstalk-ss](https://cloud.githubusercontent.com/assets/8197328/22803368/835ec2e2-eec9-11e6-84b5-70af6defdecb.PNG)

**Comment by jcheng5** [comment]
`addMarkers(data = nc_pts_WGS84)` needs to be `addMarkers(data = shared_nc)`?

**Comment by tiernanmartin** [comment]
Good typo correction, but I still seem the same behavior in the output. 

Revised regex:


 ``` r
 library(crosstalk)
  library(d3scatter)
  library(leaflet)
  library(sf)
  library(tidyverse)
  
  demo(nc, ask = FALSE, echo = FALSE, verbose = FALSE)
  
  nc_pts_WGS84 <- nc %>% st_transform(4326) %>% st_centroid()
  
  shared_nc <- SharedData$new(nc_pts_WGS84)
  
  bscols(leaflet(width = "100%", height = 300) %>%
           addTiles() %>%
           addMarkers(data = shared_nc),
         d3scatter(shared_nc, ~BIR74, ~SID79, width = "100%", height = 300)
         
  )
 
```

**Comment by jcheng5** [comment]
Also `nc_pts_WGS84 <- nc %>% st_transform(4326) %>% st_centroid()` results in a sfc, it appears to helps to convert it to `sf` by adding `%>% st_sf()` to the end.

It looks like something is still missing though, I have to run but will take a look later.

**Comment by tiernanmartin** [comment]
FWIW, I just noticed that the plotly side of the output works as intended (you can select a subset of the records and that selection is reflected in the leaflet map). 

The issue seems to be with selecting from the leaflet side.

**Comment by mdsumner** [comment]
`st_centroid` should return an sf when given one, though the update was relatively recent (since 0.3-0 I believ): 

https://github.com/edzer/sfr/pull/162

I see 

```R
library(sf)
library(dplyr)
demo(nc, ask = FALSE, echo = FALSE, verbose = FALSE)
nc_pts_WGS84 <- nc %>% st_transform(4326) %>% st_centroid()
class(nc_pts_WGS84)
#[1] "sf"         "data.frame"
packageVersion("sf")
#[1] ‘0.3.2’
```

I think there are still some functions that will only return a sfc, so please just record them as issues.  There's a general pattern in `sf` where `sfg` is elevated to `sfc` and `sf` is brought down to `sfc` to perform operations on (sets of) geometries, and it just needs a review to ensure this returns the right level for the input.   I mean to review the remaining functions and make sure that all three levels exist where appropriate but just haven't gotten to it yet. 

@edzer I might not be completely correct on some of this

**Comment by mdsumner** [comment]
And gosh, that is really cool!  Thanks for the example :)

**Comment by jcheng5** [comment]
@tiernanmartin I'll have to look into why, but it appears to work if the data argument is moved from the `addMarkers()` call to the `leaflet()` call.

**Comment by jcheng5** [comment]
I've made this a leaflet bug instead. Thanks for the report! https://github.com/rstudio/leaflet/issues/373

**Comment by edzer** [comment]
@mdsumner agreed; and @ all: pls update to sf 0.3-4 which is on cran - things have moved pretty fast lately.

**Comment by tiernanmartin** [comment]
Thanks, @jcheng5 .

Is there a reason that the linking only works with point geoms? It would be nice if the linked brushing could be used with polygons as well:

``` r
shared_nc <-  nc %>% st_transform(4326) %>% SharedData$new()

bscols(leaflet(data = shared_nc, width = "100%", height = 300) %>%
         addTiles() %>%
         addPolygons(opacity = 0,
                     fillOpacity = .85,
                     smoothFactor = 0),
       plot_ly(shared_nc_pt, x = ~BIR74, y=  ~SID79, type = 'scatter', mode = 'markers')       
)
```

![crosstalk-ss-2](https://cloud.githubusercontent.com/assets/8197328/22836467/58396ede-ef71-11e6-9f54-8c8cdf7f892e.PNG)

**Comment by tiernanmartin** [comment]
Thanks @jcheng5 .

Are there plans to extend these features to other geoms? I notice that the linking breaks down if I substitute polygons for points:

``` r
shared_nc <-  nc %>% st_transform(4326) %>% SharedData$new()

bscols(leaflet(data = shared_nc) %>%
         addTiles() %>%
         addPolygons(opacity = 1,
                     color = 'white',
                     weight = .25,
                     fillOpacity = .5,
                     fillColor = 'blue',
                     smoothFactor = 0),
       plot_ly(shared_nc, x = ~BIR74, y=  ~SID79, type = 'scatter', mode = 'markers')       
)
```
![crosstalk-ss-2](https://cloud.githubusercontent.com/assets/8197328/22836903/2e0cc528-ef73-11e6-86d3-ed9bae7fc001.PNG)

**Comment by mdsumner** [comment]
I am planning to explore this too just fyi

**Comment by tiernanmartin** [comment]
Awesome, @mdsumner! `crosstalk` has great potential to dramatically lower the technical hurdles for throwing together an insight-provoking interactive visualization. I look forward to seeing what you come up with!

**Comment by BilboBaagins** [comment]
Hi, I am just wondering if you had any luck with substituting points for polygons?

I am looking to link polygons on a leaflet map to a corresponding datatable. I was following the code in this example: [Gapminder data using crosstalk ](https://rstudio-pubs-static.s3.amazonaws.com/215948_95c1ab86ad334d2f82856d9e5ebc16af.html). 

However, this line: **sd$transform(as.data.frame)** is giving me the following error: **Error: attempt to apply non-function**.
I understand that the datatable() function needs a matrix or data frame object and that passing datatable(sd) when sd is a SpatialPolygonsDataFrame will result in an error. However, I can't seem to convert sd into a dataframe as is shown in the above example. 

I am just wondering if anyone else has encountered this ?

Thanks

**Comment by Geoyi** [comment]
@BilboBaagins if you tend to use filter_slider from crosstalk, you could do`shared_poly_df <-  'youploygonfile'  %>% as.data.frame()  %>%  SharedData$new()`
using SharedData$new() instead of SharedData$transform(). @jcheng5 has replied in other crosstalk issue, and it works for me.
However, if you wanna use leaflet to plot the polygon you need to render data from `shared_poly <-  'youploygonfile'   %>%  SharedData$new()`, in this case, polygon file did not convert to dataframe, if it makes sense.

**Comment by dmaupin12** [comment]
@BilboBaagins 
I'm still trying to figure out how to filter the polygons in leaflet.. If I use `shared_poly <- 'youploygonfile' %>% SharedData$new()`, I cannot use the select_filter(). If i use `shared_poly_df <- 'youploygonfile' %>% as.data.frame() %>% SharedData$new()`, then I can't plot in leaflet. Am I missing something?
