### ISSUE TITLE
Plotly × Leaflet: using plotly modebar removes leaflet selection

### ISSUE THREAD

**Issue by tiernanmartin** [rstudio/crosstalk#29]
When linking `plotly` and `leaflet` htmlwidgets, it appears that any use of the `plotly` [modebar](http://help.plot.ly/getting-to-know-the-plotly-modebar/) causes the `leaflet` selection to reset.

Tools like `zoom` and `pan` are quite useful for exploring dense visualizations, so the incompatibility of these tools with the `crosstalk` linking seems like a missed opportunity.

#### Regex:
``` r
library(crosstalk)
library(d3scatter)
library(leaflet)
library(sf)
library(plotly)
library(tidyverse)

demo(nc, ask = FALSE, echo = FALSE, verbose = FALSE)

shared_nc_pt <- nc %>% st_transform(4326) %>% st_centroid() %>% SharedData$new()

bscols(leaflet(data = shared_nc_pt) %>%
         addTiles() %>%
         addMarkers(),
       plot_ly(shared_nc_pt, x = ~BIR74, y=  ~SID79, type = 'scatter', mode = 'markers')       
)

```

**Comment by jcheng5** [comment]
Seems like one for @cpsievert?

**Comment by cpsievert** [comment]
Use the `highlight()` function for better control over which event clears selections:

bscols(leaflet(data = shared_nc_pt) %>%
         addTiles() %>%
         addMarkers(),
       plot_ly(shared_nc_pt, x = ~BIR74, y=  ~SID79, type = 'scatter', mode = 'markers') %>% highlight("plotly_deselect")      
)
