### ISSUE TITLE
Error: Unknown column 'g' (related to plotly?)

### ISSUE THREAD

**Issue by pbroberts** [rstudio/crosstalk#4]
Thanks for this awesome package.  I noticed a possible issue.  I have a markdown file using Crosstalk that knits fine and the control properly filters a datatable.  

Then if I add plotly I get the following: "Error: Unknown column 'g' Execution halted".  This occurs for filter_select and filter_checkbox.  I haven't tried filter_slider.

I think I installed the alternate ploty library as specified in the Readme, but I could very well be doing something wrong on my end.  I'd be happy to try to create a minimal example if you would find that helpful.

**Comment by jcheng5** [comment]
Minimal example would be super helpful--thanks!

**Comment by pbroberts** [comment]
Below is an example .rmd adding a filter_select to your plotly example. This gives "Line 6 Error: Unknown column 'g' " (sorry can't get the chunk ending ticks to appear properly in this comment).  

One other note, when I try to install your plotly branch, I get a response like "...Skipping install for github remote, the SHA1 (4502f572) has not changed...Skipping 1 unavailable package: crosstalk"

```
---
title: diamonds
output: html_document
---

```{r}
library(crosstalk)
library(plotly)

set.seed(100)
sd <- SharedData$new(diamonds[sample(nrow(diamonds), 1000), ])

filter_select("claritySelect", "Clarity", sd, "clarity")

plot_ly(sd, x = carat, y = price, text = paste("Clarity: ", clarity),
  mode = "markers", color = carat, size = carat) %>%
  layout(dragmode = "select")
```

```

**Comment by jcheng5** [comment]
This works now, though the APIs of both crosstalk and plotly have changed such that the code should now look like:

```r
filter_select("claritySelect", "Clarity", sd, ~clarity)

plot_ly(sd, x = ~carat, y = ~price, text = ~paste("Clarity: ", clarity),
  mode = "markers", color = ~carat, size = ~carat) %>%
  layout(dragmode = "select")
```

Thanks!
