### ISSUE TITLE
SharedData across shiny modules

### ISSUE THREAD

**Issue by cnjr2** [rstudio/crosstalk#40]
I am having some trouble understanding the scope of `SharedData` objects across modules. I am not 100% whether this is a shiny `callModule` question or even a `plotly` question, as it involves all three (i.e. crosstalk, plotly, modules).

Below is an app with a plotly scatterplot that has selection enabled. Whenever I select points on the graph, the selection should get updated in the `verbatimTextOutput` element.

![mozilla_firefox](https://user-images.githubusercontent.com/1436363/33827687-13135d26-de61-11e7-8f9c-2f6ac067a725.png)

This works fine without using modules:

```R
library(tidyverse)
library(plotly)
library(crosstalk)


ui <- bootstrapPage(
  wellPanel(
    plotlyOutput(outputId = "plot"),
    verbatimTextOutput(outputId = "selection")
  )
)

server <- function(input, output, session) {

  data <- mtcars %>%
    rownames_to_column("name") %>%
    SharedData$new()

  output$plot <- renderPlotly({
    plot_ly(data = data, x = ~disp, y = ~mpg, mode = "marker", type = "scatter") %>%
      highlight(on = "plotly_selected", off = "plotly_deselect")
  })

  output$selection <- renderPrint({
    print(data$selection())
  })

}


shinyApp(ui = ui, server = server)
```

This also works when using modules and passing the `SharedData` object to the module:

```R
library(tidyverse)
library(plotly)
library(crosstalk)


testModuleUI <- function(id, label = 'testModule'){
  ns <- NS(id)
  wellPanel(
    plotlyOutput(outputId = ns("plot")),
    verbatimTextOutput(outputId = ns("selection"))
  )
}

testModule <- function(input, output, session, data){

  output$plot <- renderPlotly({
    plot_ly(data = data, x = ~disp, y = ~mpg, mode = "markers", type = "scatter") %>%
      highlight(on = "plotly_selected", off = "plotly_deselect")
  })

  output$selection <- renderPrint({
    print(data$selection())
  })

}


ui <- bootstrapPage(
  testModuleUI(id = "testModule")
)

server <- function(input, output, session) {
  data <- mtcars %>%
    rownames_to_column("name") %>%
    SharedData$new()

  callModule(module = testModule, id = "testModule", data = data)
}


shinyApp(ui = ui, server = server)
```

However, when the `SharedData` is created in the module and all of a sudden the selections do not update up in the `verbatimTextOutput`.

```R
library(tidyverse)
library(plotly)
library(crosstalk)


testModuleUI <- function(id, label = 'testModule'){
  ns <- NS(id)
  wellPanel(
    plotlyOutput(outputId = ns("plot")),
    verbatimTextOutput(outputId = ns("selection"))
  )
}

testModule <- function(input, output, session){

  data <- mtcars %>%
    rownames_to_column("name") %>%
    SharedData$new()

  output$plot <- renderPlotly({
    plot_ly(data = data, x = ~disp, y = ~mpg, mode = "markers", type = "scatter") %>%
      highlight(on = "plotly_selected", off = "plotly_deselect")
  })

  output$selection <- renderPrint({
    print(data$selection())
  })

}


ui <- bootstrapPage(
  testModuleUI(id = "testModule")
)

server <- function(input, output, session) {
  callModule(module = testModule, id = "testModule")
}


shinyApp(ui = ui, server = server)
```

Where am I not understanding how this works?

Thank you for your help!

**Comment by cnjr2** [comment]
In a last test I got a new piece to the puzzle.

First I defined a`sharedData` object in the main server function (i.e. `dataset`) that consists of a `data.frame` with only a `name` column which is used as `key` and a `group`:

```
dataset <- tibble(name = rownames(mtcars)) %>%
  SharedData$new(key = ~name, group = 'testGroup')
```
Then I pass the `dataset` to the module and define a separate `sharedData` object in the module (i.e. `localDataset`) that has the comptible key and group.

```R
localDataset <- mtcars %>%
  rownames_to_column("name") %>%
  SharedData$new(key = ~name, group = 'testGroup')
```
I then use the `localDataset` that has actual data to plot to build an interactive plot with `plotly`.

Finally when I select points on the plot rendered with `localDataset`, the `dataset$selection()` gets updated and displayed, which is what I am after. However, the`localDataset$selection()` does not get updated.

For my usecase this behaviour is sufficient to achieve what I want, but I would be interested to understand this behaviour better.

Again the single file app is below:

```R
library(tidyverse)
library(plotly)
library(crosstalk)


testModuleUI <- function(id, label = 'testModule'){
  ns <- NS(id)
  wellPanel(
    plotlyOutput(outputId = ns("plot")),
    fluidRow(
      column(width = 6, verbatimTextOutput(outputId = ns("selection"))),
      column(width = 6, verbatimTextOutput(outputId = ns("localSelection")))
    )
  )
}

testModule <- function(input, output, session, dataset){

  localDataset <- mtcars %>%
    rownames_to_column("name") %>%
    SharedData$new(key = ~name, group = 'testGroup')

  output$plot <- renderPlotly({
    plot_ly(data = localDataset, x = ~disp, y = ~mpg, mode = "markers", type = "scatter") %>%
      highlight(on = "plotly_selected", off = "plotly_deselect")
  })

  # does not show and update
  output$selection <- renderPrint({
    print(dataset$selection())
  })

  # does not show and remains 'NULL'
  output$localSelection <- renderPrint({
    print(localDataset$selection())
  })

}


ui <- bootstrapPage(
  testModuleUI(id = "testModule")
)


server <- function(input, output, session) {

  dataset <- tibble(name = rownames(mtcars)) %>%
    SharedData$new(key = ~name, group = 'testGroup')

  callModule(module = testModule, id = "testModule", dataset = dataset)
}


shinyApp(ui = ui, server = server)
```

**Comment by Teebusch** [comment]
Thank you for figuring out how to get the crosstalk object to work in a module at all. I had started using a wonky workaround with `even_data()`. Did anyone find a way to keep the `SharedData` in the module (i.e. not define it in the app server code)?

**Comment by jcheng5** [comment]
@cnjr2 When the SharedValue is created, it "binds" to the active `session` object at that time. Each module has its own version of `session` that is namespaced. I think it's a defensible decision for `SharedData` objects created in different modules to be considered distinct, and also defensible for `SharedData` objects created in different modules to be considered equivalent. What's definitely weird is that they are considered equivalent from the JS side but distinct from the R side (`sd$selection()`), so this is a bug.

In the meantime I consider creating the `SharedData` in the parent and passing it to each module that needs it, to be the recommended practice.

**Comment by msaltieri** [comment]
Hello @cnjr2, have you ever find a definitive solution to this issue? What @jcheng5 proposed (defining the `SharedData` object in the main server) is not applicable when dealing with nested `shiny` modules with several levels.

In particular, it seems that, when you code something like
```
output$text <- renderText(
    shared_obj$data()
)
```
a `text` attribute is added to the JSON defining the `SharedData` object at the JS level.

In this case, when `output$text` is defined inside a `shiny` module, that object is known as `id-text` from the JS side, where `id` is the module identifier. Of course, in this case a namespace inconsistency generates.

Have you any idea of how to solve this?

**Comment by jcheng5** [comment]
@msaltieri Can you clarify—is your desired behavior that all of the modules are linked? Or that they all have a distinct SharedData that’s disconnected from the others?

**Comment by msaltieri** [comment]
Hi @jcheng5, thanks for the quick feedback.

In my opinion the best practice should be that all the modules have a distinct `SharedData` that's disconnected from the others. Then, if it's the case, it should be possible to pass the `SharedData` object from a module to another, as @cnjr2 proposed.

Anyway here the problem is that, even if in the entire project just one `SharedData` object is defined, if it is defined into a module and not in the main server, then its `$data()` method is not reactive.

**Comment by jcheng5** [comment]
Right, understood. I’m sorry I’ve let this bug sit for so long, I’ll see if I can figure it out today.

**Comment by jcheng5** [comment]
Thank you all for the feedback and your patience, should be fixed on the main branch.
