### ISSUE TITLE
Leaflet in crosstalk does not work with flexdashboard

### ISSUE THREAD

**Issue by EnricowithR** [rstudio/crosstalk#48]
Hello,

if I use your code example below it works properly. But when it is used inside flexdashboard it does not display anymore the leaflet map.
To test it just replace output: html_document with:

output: 
  flexdashboard::flex_dashboard:
    orientation: rows

 Below is the example that works without well without flexdashboard.
 ---
  title: Fiji earthquakes
 output: html_document
 ---

```{r}
library(crosstalk)
library(leaflet)
library(DT)

# Wrap data frame in SharedData
sd <- SharedData$new(quakes[sample(nrow(quakes), 100),])

# Create a filter input
filter_slider("mag", "Magnitude", sd, column=~mag, step=0.1, width=250)

# Use SharedData like a dataframe with Crosstalk-enabled widgets
bscols(
  leaflet(sd) %>% addTiles() %>% addMarkers(),
  datatable(sd, extensions="Scroller", style="bootstrap", class="compact", width="100%",
    options=list(deferRender=TRUE, scrollY=300, scroller=TRUE))
)
```

**Comment by jcheng5** [comment]
Can you try without bscols? Just use flexdashboard's own row/column features.

**Comment by EnricowithR** [comment]
thank you for the quick reply! That made the trick!

**Comment by jcheng5** [comment]
Great, thanks!
