### ISSUE TITLE
'Crosstalk cannot be unloaded'

### ISSUE THREAD

**Issue by rlamb01** [rstudio/crosstalk#77]
Running the example code from: https://rstudio.github.io/crosstalk/using.html

```
devtools::install_github("rstudio/crosstalk")

devtools::install_github("jcheng5/d3scatter")

library(crosstalk)

shared_iris <- SharedData$new(iris)
d3scatter(shared_iris, ~Petal.Length, ~Petal.Width, ~Species)
```

I get the following error:
Error in value[[3L]](cond) : 
  Package ‘crosstalk’ version 1.0.0 cannot be unloaded:
 Error in unloadNamespace(package) : namespace ‘crosstalk’ is imported by ‘d3scatter’, ‘leaflet’ so cannot be unloaded

![Capture](https://user-images.githubusercontent.com/56387150/68468395-dd5f5980-020f-11ea-9ae6-fe645183a427.PNG)

**Comment by cpsievert** [comment]
Restarting R should fix this issue
