### ISSUE TITLE
Selecting which columns to plot

### ISSUE THREAD

**Issue by guffrann9** [rstudio/crosstalk#90]
Hi,

I have recently started using crosstalk and I would like to have a select box which has my tables columns as boxes and showing up the graphs that user chooses. I tried doing it by this 

"filter_checkbox('select_samples', 'select_samples', sd, ~colnames, allLevels = FALSE, inline = FALSE, columns = 1)"
"filter_checkbox('select_samples', 'select_samples', sd, ~colnames(), allLevels = FALSE, inline = FALSE, columns = 1)"
"filter_checkbox('select_samples', 'select_samples', sd, ~colnames(sd), allLevels = FALSE, inline = FALSE, columns = 1)"

none of them worked the errors that raise was

1st one Error in unique.default(group) : unique() applies only to vectors
2nd one Error in is.data.frame(x) : argument "x" is missing, with no default
3rd one Error in makeGroupOptions(sharedData, group, allLevels) : 
  Can't form options with zero-length group vector

any ideas or solutions are appreciated.

Thanks in advance

**Comment by jcheng5** [comment]
This isn't likely to work the way you want; `filter_checkbox` is meant to filter rows, not columns. You have a couple of options:

1. If possible, [pivot your data from wide to long](https://tidyr.tidyverse.org/articles/pivot.html). This only works if all the columns are being drawn in the same plot, and have the same data type and scale. (e.g. this would work great if each of your columns represent a certain year)
2. If those assumptions aren't met, you could use Shiny, which is much more powerful than crosstalk.
